name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_COMPOSE_COMMAND: docker-compose -f docker-compose.yaml
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - fabos-nexus-adapter
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: $DOCKER_COMPOSE_COMMAND build --no-cache ${{ matrix.service }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME  }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD  }}
      - name: Push docker image
        run: $DOCKER_COMPOSE_COMMAND push ${{ matrix.service }}
